packages = [
    "pandas",
    "pyabc2==0.1.0.dev2",
    "trad-setlist-helper==0.0.2.dev2",
]
[files]
"https://raw.githubusercontent.com/adactio/TheSession-data/main/json/aliases.json" = ""
"https://raw.githubusercontent.com/adactio/TheSession-data/main/json/tunes.json" = ""
# "{FROM}" = "../src/trad_setlist_helper"
# "{TO}" = "./trad_setlist_helper/"
# "{FROM}/__init__.py" = ""
# "{FROM}/html.py" = ""
